source "http://rubygems.org"

gem "rdoc"
gem "rails", "2.3.14"
gem "sqlite3"

gem "bushido", :path => "../../../"

group :development, :test do
  gem "rspec"
  gem "rspec-rails", "1.3.4"
  gem "capybara", "0.3.9"
end
